#!/usr/bin/env bash

# Source: depesz.com/2013/09/11/how-to-make-backups-of-postgresql/

set -o errexit
set -o nounset

declare -r backups_dir=/home/backups/postgresql
declare -r current_backup_dir=${backups_dir}/$(date +%Y-%m-%d)

mkdir -p "${current_backup_dir}" && cd "${current_backup_dir}"

psql postgres \
	--quiet \
	--no-align \
	--tuples-only \
	--no-psqlrc \
	--command "select datname from pg_database where datallowconn" | \
	xargs \
		--delimiter '\n' \
		-I{} \
		--max-procs 2 \
		pg_dump \
			--data-only \
			--no-owner \
			--no-privileges \
			--file {}.sql {}

cd "${backups_dir}"
find . -mindepth 2 \
	-maxdepth 2 \
	-type f \
	-regex '\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/.*sql' \
	-mtime +6 \
	-delete
find . -mindepth 1 \
	-maxdepth 1 \
	-type d \
	-regex '\./[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' \
	-empty \
	-delete
